---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: asampleapp-prod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: asampleapp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: charts
  interval: 1m0s
  targetNamespace: production
